<p class="eyebrow">Portal Pemohon ITR</p><h2>Dashboard</h2>
<p class="section-lead">Selamat datang, <?= htmlspecialchars($nama_pengguna,ENT_QUOTES,'UTF-8') ?>. Pantau pengajuan dan aktivitas akun Anda di sini.</p>
<?php if($this->session->flashdata('sukses')): ?><div class="notice"><?= htmlspecialchars($this->session->flashdata('sukses'),ENT_QUOTES,'UTF-8') ?></div><?php endif; ?>
<div class="itr-summary"><article><strong><?= count($pengajuan_itr) ?></strong><span>Total Pengajuan</span></article><article><strong><?= count(array_filter($pengajuan_itr,function($r){return $r['status']==='diajukan';})) ?></strong><span>Diajukan</span></article></div>
<a class="btn btn-gold" href="<?= base_url('pemohon/pengajuan_itr') ?>">+ PENGAJUAN ITR</a>
<style>
.dash-wrap .info-card table{display:table;width:100%;max-width:none;table-layout:fixed;border-collapse:collapse}.dash-wrap .info-card th,.dash-wrap .info-card td{padding:18px 16px;text-align:left;vertical-align:middle;overflow-wrap:anywhere}.dash-wrap .info-card th:nth-child(1){width:16%}.dash-wrap .info-card th:nth-child(2){width:11%}.dash-wrap .info-card th:nth-child(3){width:29%}.dash-wrap .info-card th:nth-child(4){width:15%}.dash-wrap .info-card th:nth-child(5){width:10%}.dash-wrap .info-card th:nth-child(6){width:19%}@media(max-width:900px){.dash-wrap .info-card table{min-width:840px}}
</style>
<?php $this->load->view('partials/pemohon_itr_pesan'); ?>
<div class="info-card"><h3>Riwayat Pengajuan ITR</h3><?php if(!$pengajuan_itr): ?><p>Belum ada pengajuan. Mulai melalui menu PENGAJUAN ITR.</p><?php else: ?><div style="overflow:auto"><table><thead><tr><th>No. Permohonan</th><th>Jenis</th><th>Lokasi</th><th>Tanggal</th><th>Status</th><th>Berkas</th></tr></thead><tbody><?php foreach($pengajuan_itr as $r): $perusahaan=($r['jenis_pemohon']??'perorangan')==='perusahaan'; $berkas=array('file_permohonan'=>'Permohonan','file_ktp'=>'KTP','file_sertifikat'=>'Sertifikat','file_siteplan'=>'Site plan','file_denah_foto'=>'Denah & Foto'); if($perusahaan)$berkas+=array('file_nib'=>'NIB','file_npwp'=>'NPWP','file_akta'=>'Akta'); ?><tr><td><?= htmlspecialchars($r['no_permohonan']) ?></td><td><?= $perusahaan?'Perusahaan':'Perorangan' ?></td><td><?= htmlspecialchars($r['alamat_lokasi']) ?></td><td><?= date('d/m/Y H:i',strtotime($r['created_at'])) ?></td><td><?= htmlspecialchars(ucfirst($r['status'])) ?></td><td><?php foreach($berkas as $field=>$label): if(empty($r[$field]))continue; ?><a href="<?= base_url('pemohon/berkas_itr/'.$r['id'].'/'.$field) ?>"><?= $label ?></a><br><?php endforeach; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
<div class="info-card"><h3>Aktivitas Anda</h3><?php if(!$aktivitas_itr): ?><p>Belum ada aktivitas pengajuan tercatat.</p><?php else: ?><ul class="itr-activity"><?php foreach($aktivitas_itr as $activity): ?><li><p><?= htmlspecialchars($activity['keterangan']) ?></p><small><?= date('d/m/Y H:i',strtotime($activity['created_at'])) ?></small></li><?php endforeach; ?></ul><?php endif; ?></div>
<style>.itr-summary{display:grid;grid-template-columns:repeat(2,1fr);gap:20px;margin:28px 0}.itr-summary article{padding:24px;border:1px solid var(--line);border-radius:16px;background:var(--surface)}.itr-summary strong{display:block;font:400 40px var(--display);color:var(--gold-300)}.itr-summary span{font-size:14px;color:var(--muted)}.itr-activity{list-style:none;padding:0}.itr-activity li{padding:16px 0;border-bottom:1px solid var(--line)}.itr-activity p{margin:0 0 4px}.itr-activity small{color:var(--muted)}@media(max-width:600px){.itr-summary{grid-template-columns:1fr}}</style>
