<?php $v=function($field,$default='')use($old){return htmlspecialchars(isset($old[$field])?$old[$field]:$default,ENT_QUOTES,'UTF-8');}; ?>
<p class="eyebrow">Portal Pemohon ITR</p><h2>Formulir Pengajuan ITR</h2><p class="section-lead">Lengkapi data lokasi, rencana kegiatan, dan seluruh lampiran sebelum mengirim pengajuan.</p>
<?php if($error): ?><div class="notice" role="alert"><?= htmlspecialchars($error,ENT_QUOTES,'UTF-8') ?> Pilih kembali lampiran sebelum mengirim ulang.</div><?php endif; ?>
<?= form_open_multipart('pemohon/simpan_itr',array('class'=>'info-card itr-application')) ?>
<input type="hidden" name="itr_token" value="<?= htmlspecialchars($this->session->userdata('itr_form_token'),ENT_QUOTES,'UTF-8') ?>">
<h3>Data Pemohon</h3><div class="itr-form-grid">
<?php foreach(array('nama_pemohon'=>'Nama Pemohon','nik'=>'NIK','no_hp'=>'Nomor HP','email'=>'Email') as $field=>$label): ?><div><label for="itr-<?= $field ?>"><?= $label ?> *</label><input id="itr-<?= $field ?>" name="<?= $field ?>" type="<?= $field==='email'?'email':($field==='no_hp'?'tel':'text') ?>" value="<?= $v($field,$field==='nama_pemohon'?$nama_pengguna:($field==='email'?$email_pengguna:'')) ?>" <?= $field==='nik'?'pattern="[0-9]{16}" maxlength="16" inputmode="numeric"':'' ?> required></div><?php endforeach; ?>
</div><h3>Lokasi dan Rencana Kegiatan</h3><div class="itr-form-grid">
<div class="itr-full"><label for="itr-alamat">Alamat Lokasi *</label><textarea id="itr-alamat" name="alamat_lokasi" required><?= $v('alamat_lokasi') ?></textarea></div>
<div><label for="itr-luas">Luas Lahan (m²) *</label><input id="itr-luas" type="number" name="luas_lahan" min="0.01" step="0.01" value="<?= $v('luas_lahan') ?>" required></div>
<div><label for="itr-lat">Latitude *</label><input id="itr-lat" type="number" name="latitude" min="-90" max="90" step="any" placeholder="-7.7267" value="<?= $v('latitude') ?>" required></div>
<div><label for="itr-lng">Longitude *</label><input id="itr-lng" type="number" name="longitude" min="-180" max="180" step="any" placeholder="109.0154" value="<?= $v('longitude') ?>" required></div>
<div class="itr-full"><label for="itr-rencana">Rencana Kegiatan *</label><textarea id="itr-rencana" name="rencana_kegiatan" required><?= $v('rencana_kegiatan') ?></textarea></div></div>
<h3>Lampiran Persyaratan</h3><p>PDF, JPG, atau PNG. Maksimum 100 MB per berkas. Semua lampiran wajib diunggah.</p><div class="itr-form-grid">
<?php foreach(array('file_permohonan'=>'Surat / Formulir Permohonan Bertanda Tangan','file_ktp'=>'KTP Pemohon','file_sertifikat'=>'Sertifikat Tanah / Lahan','file_siteplan'=>'Gambar Rencana Tapak (Site Plan)') as $field=>$label): ?><div><label for="itr-<?= $field ?>"><?= $label ?> *</label><input id="itr-<?= $field ?>" type="file" name="<?= $field ?>" accept=".pdf,.jpg,.jpeg,.png" required></div><?php endforeach; ?></div>
<div class="itr-form-actions"><button type="submit" class="btn btn-gold">Kirim Pengajuan ITR</button><a class="btn btn-ghost" href="<?= base_url('pemohon') ?>">Kembali ke Dashboard</a></div><?= form_close() ?>
<style>.itr-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin:22px 0 32px}.itr-full{grid-column:1/-1}.itr-application label{display:block;margin-bottom:8px;font-size:15px;color:var(--gold-300)}.itr-application input:not([type=hidden]),.itr-application textarea{width:100%;padding:14px;border:1px solid var(--line);border-radius:10px;background:var(--input);color:var(--text);font:400 15px var(--body)}.itr-application textarea{min-height:110px}.itr-form-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}@media(max-width:700px){.itr-form-grid{grid-template-columns:1fr}.itr-full{grid-column:auto}}</style>
