---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/sipgatutkaca.sigaru.my.id/ && tar --exclude='.git' --exclude='.github' --exclude='application/config/database.php' --exclude='deploy-hook.config.php' --exclude='deploy-hook.log' --exclude='deploy-hook.lock' -cf - . | (mkdir -p "$DEPLOYPATH" && cd "$DEPLOYPATH" && tar xf -)
