<?php $heading='Pengajuan PBG'; $top_actions='<a class="btn btn-primary" href="'.base_url('pengajuan-pbg/tambah').'">+ Tambah Pengajuan</a>'; $this->load->view('pbg_pu/header',compact('heading','top_actions','nama_pengguna')); ?>
<style>
.pbg-list-card{padding:32px}.pbg-list-toolbar{display:flex;align-items:center;justify-content:space-between;gap:24px;margin-bottom:24px}.pbg-list-toolbar .eyebrow{margin:0}.pbg-list-toolbar .search{flex:0 1 390px}.pbg-list-table{table-layout:fixed;min-width:0}.pbg-list-table th,.pbg-list-table td{padding:18px 14px;overflow-wrap:anywhere}.pbg-list-table th:nth-child(1){width:7%}.pbg-list-table th:nth-child(2){width:15%}.pbg-list-table th:nth-child(3){width:15%}.pbg-list-table th:nth-child(4){width:21%}.pbg-list-table th:nth-child(5){width:11%}.pbg-list-table th:nth-child(6){width:12%}.pbg-list-table th:nth-child(7){width:19%}.pbg-list-table .actions{align-items:flex-start}.pbg-list-table .actions .btn{min-height:36px;padding:0 14px;font-size:9px;letter-spacing:.1em}.pbg-list-table .locked{display:inline-block;padding:8px 0;color:#8b9da8;font-size:12px}.pbg-list-empty{text-align:center;padding:46px!important}
@media(max-width:1250px){.pbg-list-table th,.pbg-list-table td{padding:15px 10px;font-size:12px}.pbg-list-table .actions .btn{padding:0 10px}}
@media(max-width:820px){.pbg-list-card{padding:18px}.pbg-list-toolbar{align-items:stretch;flex-direction:column}.pbg-list-toolbar .search{flex:auto;width:100%}.pbg-list-table,.pbg-list-table tbody,.pbg-list-table tr,.pbg-list-table td{display:block;width:100%}.pbg-list-table thead{display:none}.pbg-list-table tr{padding:18px;border-bottom:1px solid var(--line)}.pbg-list-table td{display:grid;grid-template-columns:120px 1fr;gap:12px;padding:8px 0;border:0}.pbg-list-table td:before{content:attr(data-label);color:var(--gold);font:400 12px var(--display);letter-spacing:.05em;text-transform:uppercase}.pbg-list-table .actions{display:flex}.pbg-list-table td:last-child{display:grid}.pbg-list-table td:last-child .actions{grid-column:2}.pbg-list-empty{display:block!important}.pbg-list-empty:before{display:none}}
</style>
<?php if($this->session->flashdata('sukses')):?><div class="notice"><?= htmlspecialchars($this->session->flashdata('sukses')) ?></div><?php endif;?>
<div class="card pbg-list-card"><div class="pbg-list-toolbar"><p class="eyebrow">Daftar Permohonan</p><input class="search" id="q" placeholder="Cari nama pemohon atau alamat..."></div><div class="table-wrap"><table id="table" class="pbg-list-table"><thead><tr><th>Jenis</th><th>No. Permohonan</th><th>Nama Pemohon</th><th>Alamat</th><th>Tanggal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
<?php if(empty($daftar)):?><tr><td class="pbg-list-empty" colspan="7">Belum ada pengajuan. Klik <b>+ Tambah Pengajuan</b> untuk mulai.</td></tr><?php endif;?>
<?php foreach($daftar as $r):?><tr><td data-label="Jenis"><span class="badge diajukan">PBG</span></td><td data-label="No. Permohonan"><?= htmlspecialchars($r['no_permohonan']) ?></td><td data-label="Nama Pemohon"><?= htmlspecialchars($r['nama_pemohon']) ?></td><td data-label="Alamat"><?= htmlspecialchars($r['alamat_bangunan']) ?></td><td data-label="Tanggal"><?= date('d/m/Y',strtotime($r['created_at'])) ?></td><td data-label="Status"><span class="badge <?= $r['status'] ?>"><?= ucfirst($r['status']) ?></span></td><td data-label="Aksi"><div class="actions"><a class="btn" href="<?= base_url('pengajuan-pbg/tahap/'.$r['id']) ?>">Lihat</a><?php if($r['status']==='diajukan'):?><a class="btn" href="<?= base_url('pengajuan-pbg/edit/'.$r['id']) ?>">Edit</a><a class="btn btn-danger" onclick="return confirm('Hapus pengajuan ini?')" href="<?= base_url('pengajuan-pbg/hapus/'.$r['id']) ?>">Hapus</a><?php else:?><span class="locked">Terkunci</span><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div></div>
<script>q.oninput=()=>{let x=q.value.toLowerCase();document.querySelectorAll('#table tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(x)?'':'none')}</script>
<?php $this->load->view('pbg_pu/footer'); ?>
