<?php $heading='Tahapan Pengajuan PBG'; $top_actions='<a class="btn" href="'.base_url('pengajuan-pbg').'">Kembali ke Daftar</a>'; $this->load->view('pbg_pu/header',compact('heading','top_actions','nama_pengguna')); $labels=array(1=>'Pendaftaran Permohonan',2=>'Pemeriksaan Kelengkapan Data',3=>'Verifikasi Hasil Perbaikan',4=>'Pemeriksaan Selesai'); ?>
<?php if($this->session->flashdata('sukses')):?><div class="notice"><?= htmlspecialchars($this->session->flashdata('sukses')) ?></div><?php endif;?>
<?php
$timeline = array(
  1 => array('Pendaftaran Permohonan','Permohonan PBG berhasil didaftarkan.','<rect x="6" y="3" width="12" height="18" rx="1.5"/><path d="M9 4.5V4a1.5 1.5 0 011.5-1.5h3A1.5 1.5 0 0115 4v.5"/><path d="M9 13l2.2 2.2L15.5 11"/>'),
  2 => array('Pemeriksaan Kelengkapan Data','PU memeriksa kelengkapan data dan dokumen.','<circle cx="10.5" cy="10.5" r="6"/><path d="M15 15l5 5"/>'),
  3 => array('Verifikasi Hasil Perbaikan','PU memverifikasi hasil perbaikan yang diterima.','<rect x="6" y="3" width="12" height="18" rx="1.5"/><path d="M8.5 8h7M8.5 11h7M8.5 15l2.3 2.3 4.7-5"/>'),
  4 => array('Pemeriksaan Selesai','Pemeriksaan data dan dokumen telah selesai.','<circle cx="12" cy="9" r="5.5"/><path d="M9 13.8L7 21l5-2.6 5 2.6-2-7.2"/><path d="M9.7 9.2l1.6 1.6 3-3.2"/>'),
);
?>
<nav class="timeline-card timeline-top" aria-label="Navigasi tahapan PBG"><div class="proses-timeline">
<?php foreach($timeline as $n=>$item): $state=$n<(int)$row['tahap']?'done':($n===(int)$row['tahap']?($row['status']==='ditolak'?'rejected':($row['status']==='disetujui'?'done':'current')):'pending'); ?>
<a class="proses-item <?= $state ?>" href="<?= base_url('pengajuan-pbg/tahap/'.$row['id'].'/'.$n) ?>"><span class="proses-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><?= $item[2] ?></svg></span><span class="proses-body"><b><?= $n ?>. <?= htmlspecialchars($item[0]) ?></b><small><?= htmlspecialchars($item[1]) ?></small></span></a>
<?php endforeach;?></div></nav>
<?php $wajib=array('file_ktp','file_kepemilikan_tanah','file_data_perencana','file_pkkpr','file_rencana_teknis','file_teknis_struktur','file_checklist_mep','file_pernyataan_tataruang'); $lengkap=0; foreach($wajib as $f){if(!empty($row[$f]))$lengkap++;} $semua_lengkap=$lengkap===count($wajib); ?>
<div class="card applicant-card"><div class="applicant-head"><div><span class="badge diajukan">PBG</span><strong><?= htmlspecialchars($row['no_permohonan']) ?></strong></div><span class="badge <?= $row['status'] ?>"><?= ucfirst($row['status']) ?></span></div><div class="detail-grid"><div><small>Nama Pemohon</small><?= htmlspecialchars($row['nama_pemohon']) ?></div><div><small>NIK</small><?= htmlspecialchars($row['nik']?:'—') ?></div><div><small>Nomor HP</small><?= htmlspecialchars($row['no_hp']) ?></div><div><small>Email</small><?= htmlspecialchars($row['email']?:'—') ?></div><div class="full"><small>Alamat Bangunan</small><?= htmlspecialchars($row['alamat_bangunan']) ?></div><div><small>Jenis Bangunan</small><?= htmlspecialchars($row['jenis_bangunan']) ?></div><div><small>Kategori</small><?= ucwords(str_replace('_',' ',$row['kategori_bangunan'])) ?></div><div><small>Tanggal Pengajuan</small><?= date('d/m/Y H:i',strtotime($row['created_at'])) ?></div></div></div>

<div class="card stage-card"><div class="stage-heading"><div><p class="eyebrow">Tahap <?= $tahap ?></p><h2><?= $labels[$tahap] ?></h2></div><?php if($tahap<=2):?><span class="badge <?= $semua_lengkap?'disetujui':'diajukan' ?>"><?= $lengkap ?>/<?= count($wajib) ?> dokumen wajib</span><?php endif;?></div>
<?php if($tahap<=2):?><div class="document-groups"><?php $groups=array('Dokumen Umum'=>array('file_ktp','file_kepemilikan_tanah','file_data_perencana','file_pernyataan_tataruang'),'Bidang Arsitektur & Tata Ruang'=>array('file_pkkpr','file_rencana_teknis','file_dokumen_lingkungan'),'Bidang Struktur'=>array('file_teknis_struktur'),'Bidang MEP'=>array('file_checklist_mep')); foreach($groups as $group=>$fields):?><section><h3><?= $group ?></h3><ul class="doc-list"><?php foreach($fields as $f): $ada=!empty($row[$f]);?><li class="<?= $ada?'ok':'missing' ?>"><span class="doc-icon"><?= $ada?'✓':'!' ?></span><span><b><?= htmlspecialchars($files[$f]) ?></b><small><?= in_array($f,$wajib,true)?'Wajib':'Opsional' ?></small></span><?php if($ada):?><button type="button" class="view-file" data-file-url="<?= base_url('assets/uploads/pbg/'.rawurlencode($row[$f])) ?>" data-file-title="<?= htmlspecialchars($files[$f],ENT_QUOTES,'UTF-8') ?>">Lihat Berkas</button><?php else:?><em>Belum diunggah</em><?php endif;?></li><?php endforeach;?></ul></section><?php endforeach;?></div>
<?php if(!empty($row['catatan_admin'])):?><div class="notice"><b>Catatan PU terakhir</b><br><?= nl2br(htmlspecialchars($row['catatan_admin'])) ?></div><?php endif;?>
<div class="decision-actions"><?php if($tahap===1):?><?= form_open('pengajuan-pbg/ubah-tahap/'.$row['id']) ?><input type="hidden" name="tahap" value="2"><input type="hidden" name="status" value="diverifikasi"><button class="btn btn-primary" <?= !$semua_lengkap?'disabled title="Dokumen wajib belum lengkap"':'' ?>>Berkas Lengkap, Lanjut</button><?= form_close() ?><button class="btn note-toggle" type="button">Berkas Belum Lengkap</button><?php else:?><?= form_open('pengajuan-pbg/ubah-tahap/'.$row['id']) ?><input type="hidden" name="tahap" value="3"><input type="hidden" name="status" value="diverifikasi"><button class="btn btn-primary">Berkas Sudah Benar</button><?= form_close() ?><button class="btn note-toggle" type="button">Berkas Masih Salah</button><?php endif;?></div>
<div class="note-panel" hidden><?= form_open('pengajuan-pbg/ubah-tahap/'.$row['id']) ?><input type="hidden" name="tahap" value="<?= $tahap ?>"><input type="hidden" name="status" value="diverifikasi"><label>Keterangan untuk Pemohon</label><textarea name="catatan" required placeholder="Jelaskan dokumen yang kurang atau harus diperbaiki."></textarea><button class="btn" style="margin-top:10px">Simpan Keterangan</button><?= form_close() ?></div>
<?php elseif($tahap===3):?><p>PU memilih Tim Profesi Ahli untuk konsultasi teknis pada setiap bidang. Bidang yang telah direkomendasikan otomatis dikunci.</p>
<?php $ada_perbaikan=false;$menunggu_review=false;foreach($konsultasi_terakhir as $k){if($k['status']==='perlu_perbaikan')$ada_perbaikan=true;if($k['status']==='ditugaskan')$menunggu_review=true;} ?>
<?php if($ada_perbaikan):?><div class="revision-alert"><div><b>Perbaikan diperlukan</b><p>Perbarui data atau unggah berkas pengganti untuk bidang yang berstatus Perlu Perbaikan.</p></div><a class="btn btn-primary" href="<?= base_url('pengajuan-pbg/edit/'.$row['id']) ?>">Perbaiki Data / Berkas</a></div><?php endif;?>
<?php if(!$konsultasi_selesai):?><?= form_open_multipart('pengajuan-pbg/konsultasi/'.$row['id']) ?><div class="tpa-grid"><?php foreach(array('arsitektur'=>'Arsitektur & Tata Ruang','struktur'=>'Struktur','mep'=>'Mekanikal, Elektrikal & Perpipaan (MEP)') as $kode=>$nama): $akhir=$konsultasi_terakhir[$kode]??null;?><div><label>TPA <?= $nama ?></label><?php if($akhir&&$akhir['status']==='direkomendasikan'):?><div class="tpa-locked"><span class="badge disetujui">✓ Direkomendasikan</span><small><?= htmlspecialchars($akhir['nama_tpa']??'TPA bidang telah selesai') ?> — tidak dipilih lagi pada putaran berikutnya.</small></div><?php else:?><select name="tpa_<?= $kode ?>" required <?= $akhir&&$akhir['status']==='perlu_perbaikan'&&empty($akhir['perbaikan_dikirim_at'])?'disabled':'' ?>><option value="">— Pilih TPA —</option><?php foreach($tpa_per_bidang[$kode] as $tpa):?><option value="<?= (int)$tpa['id'] ?>" <?= $akhir&&(int)$akhir['tpa_user_id']===(int)$tpa['id']?'selected':'' ?>><?= htmlspecialchars($tpa['nama']) ?> (<?= htmlspecialchars($tpa['email']) ?>)</option><?php endforeach;?></select><?php if($akhir&&$akhir['status']==='perlu_perbaikan'&&empty($akhir['perbaikan_dikirim_at'])):?><small class="field-warning">Kirim perbaikan dahulu sebelum konsultasi ulang.</small><?php endif;?><?php endif;?></div><?php endforeach;?></div><div class="consultation-fields"><div><label>Komentar untuk TPA</label><textarea name="komentar_pu" placeholder="Fokus pemeriksaan atau konteks yang perlu diperhatikan TPA."></textarea></div><div><label>Pernyataan PU</label><textarea name="pernyataan_pu" placeholder="Instruksi resmi untuk putaran konsultasi ini."></textarea></div><div class="full"><label>Lampiran Konsultasi</label><label class="dropzone"><input type="file" name="file_konsultasi" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png"><span>↑</span><b>Unggah lampiran konsultasi</b><small>PDF, DOC/DOCX, JPG atau PNG · maksimal 10 MB</small></label></div></div><button class="btn btn-primary" <?= $menunggu_review||($ada_perbaikan&&!array_filter($konsultasi_terakhir,function($k){return $k['status']==='perlu_perbaikan'&&!empty($k['perbaikan_dikirim_at']);}))?'disabled':'' ?>>Ajukan Konsultasi Berikutnya</button><?= form_close() ?><?php else:?><div class="notice"><b>Konsultasi selesai.</b> Ketiga bidang telah berstatus Direkomendasikan.</div><?php endif;?>
<h2 class="section-title">Riwayat Konsultasi</h2><?php if(empty($konsultasi)):?><div class="notice">Belum ada putaran konsultasi untuk permohonan ini.</div><?php else:?><div class="table-wrap"><table class="consultation-table"><thead><tr><th>Putaran</th><th>Bidang</th><th>TPA</th><th>Status</th><th>Ditugaskan</th></tr></thead><tbody><?php foreach($konsultasi as $k):?><tr><td><?= (int)$k['putaran'] ?></td><td><?= ucfirst($k['bidang']) ?></td><td><b><?= htmlspecialchars($k['nama_tpa']) ?></b><br><small><?= htmlspecialchars($k['email_tpa']) ?></small></td><td><span class="badge <?= $k['status']==='direkomendasikan'?'disetujui':'diverifikasi' ?>"><?= ucwords(str_replace('_',' ',$k['status'])) ?></span></td><td><?= date('d/m/Y H:i',strtotime($k['assigned_at'])) ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?><div class="decision-actions"><?= form_open('pengajuan-pbg/ubah-tahap/'.$row['id']) ?><input type="hidden" name="tahap" value="4"><input type="hidden" name="status" value="disetujui"><button class="btn" <?= !$konsultasi_selesai?'disabled title="Ketiga bidang TPA harus berstatus Direkomendasikan"':'' ?>>Proses Selesai</button><?= form_close() ?></div>
<?php else:?><div class="detail-grid"><div><small>No. Permohonan</small><?= htmlspecialchars($row['no_permohonan']) ?></div><div><small>Keputusan</small><span class="badge <?= $row['status'] ?>"><?= ucfirst($row['status']) ?></span></div><div class="full"><small>Catatan keputusan</small><?= nl2br(htmlspecialchars($row['catatan_admin']?:'—')) ?></div></div><?php endif;?></div>

<?php if(!empty($riwayat)):?><h2 class="section-title">Riwayat Tahapan</h2><div class="table-wrap"><table style="min-width:700px"><thead><tr><th>Tanggal</th><th>Tahap</th><th>Status</th><th>Catatan</th><th>Petugas PU</th></tr></thead><tbody><?php foreach($riwayat as $r):?><tr><td><?= date('d/m/Y H:i',strtotime($r['created_at'])) ?></td><td><?= $r['tahap'] ?></td><td><?= ucfirst($r['status']) ?></td><td><?= htmlspecialchars($r['keterangan']) ?></td><td><?= htmlspecialchars($r['actor']) ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>

<section class="timeline-card" aria-labelledby="judulTimeline"><p class="eyebrow">Progres Permohonan</p><h2 id="judulTimeline">Tahapan Proses PBG</h2><div class="proses-timeline">
<?php foreach($timeline as $n=>$item): $state=$n<(int)$row['tahap']?'done':($n===(int)$row['tahap']?($row['status']==='ditolak'?'rejected':($row['status']==='disetujui'?'done':'current')):'pending'); ?>
<a class="proses-item <?= $state ?>" href="<?= base_url('pengajuan-pbg/tahap/'.$row['id'].'/'.$n) ?>"><span class="proses-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><?= $item[2] ?></svg></span><span class="proses-body"><b><?= $n ?>. <?= htmlspecialchars($item[0]) ?></b><small><?= htmlspecialchars($item[1]) ?></small></span></a>
<?php endforeach;?></div></section><div class="file-modal" id="fileModal" aria-hidden="true"><div class="file-modal-backdrop" data-modal-close></div><div class="file-modal-dialog" role="dialog" aria-modal="true" aria-labelledby="fileModalTitle"><header><strong id="fileModalTitle">Pratinjau Berkas</strong><button type="button" data-modal-close aria-label="Tutup">×</button></header><div class="file-modal-body" id="fileModalBody"></div><footer><a class="btn" id="fileModalOpen" href="#" target="_blank" rel="noopener">Buka di Tab Baru</a><button class="btn" type="button" data-modal-close>Tutup</button></footer></div></div>
<style>
.timeline-top{margin:0 0 24px;padding:22px 26px}.timeline-top .proses-timeline{padding-bottom:4px}.timeline-top .proses-body small{font-size:10px}
.revision-alert{display:flex;align-items:center;justify-content:space-between;gap:18px;margin:20px 0;padding:20px;border:1px solid #e2b05f;background:#fff8e9}.revision-alert b{font:400 18px var(--display);color:#a96c17}.revision-alert p{margin:4px 0 0;color:var(--muted);font-size:12px}.tpa-locked{display:grid;gap:8px;min-height:50px}.tpa-locked small{color:var(--muted);line-height:1.5}
.tpa-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:24px 0}.tpa-grid>div{padding:18px;border:1px solid var(--line);background:#fbfdfd}.field-warning{display:block;margin-top:7px;color:#c94d5f}.consultation-fields{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:22px 0}.dropzone{display:grid;justify-items:center;gap:5px;padding:24px;border:1px dashed var(--gold);background:#faf7ed;text-align:center;cursor:pointer}.dropzone input{position:absolute;width:1px;height:1px;opacity:0}.dropzone span{display:grid;place-items:center;width:38px;height:38px;border-radius:50%;background:var(--gold);color:#fff;font-size:21px}.dropzone b{color:var(--text)}.dropzone small{font:300 11px var(--body);color:var(--muted)}.consultation-table{min-width:760px}.consultation-table small{color:var(--muted)}
.view-file{padding:5px 0;border:0;border-bottom:1px solid var(--gold);background:none;color:var(--gold);font:500 10px var(--body);letter-spacing:.08em;text-transform:uppercase;cursor:pointer}.view-file:hover{color:var(--text);border-color:var(--text)}.file-modal{position:fixed;z-index:200;inset:0;display:none;align-items:center;justify-content:center;padding:24px}.file-modal.open{display:flex}.file-modal-backdrop{position:absolute;inset:0;background:rgba(13,35,51,.68);backdrop-filter:blur(3px)}.file-modal-dialog{position:relative;width:min(900px,96vw);max-height:92vh;display:flex;flex-direction:column;background:#fff;box-shadow:0 24px 70px rgba(0,0,0,.35)}.file-modal-dialog header,.file-modal-dialog footer{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 20px;border-bottom:1px solid var(--line)}.file-modal-dialog footer{justify-content:flex-end;border-top:1px solid var(--line);border-bottom:0}.file-modal-dialog header strong{font:400 18px var(--display);color:var(--gold)}.file-modal-dialog header button{width:36px;height:36px;border:0;background:#f1f5f6;color:var(--text);font-size:24px;cursor:pointer}.file-modal-body{min-height:300px;overflow:auto;padding:18px;background:#eef3f5;text-align:center}.file-modal-body img{display:block;max-width:100%;max-height:65vh;margin:auto;object-fit:contain}.file-modal-body iframe{width:100%;height:65vh;border:0;background:#fff}
.applicant-card{margin-bottom:24px}.applicant-head,.stage-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:22px}.applicant-head>div{display:flex;align-items:center;gap:12px}.stage-heading h2{margin:4px 0 0;font:400 27px var(--display)}.document-groups{display:grid;grid-template-columns:1fr 1fr;gap:22px}.document-groups section{min-width:0}.document-groups h3{font:400 17px var(--display);color:var(--gold);border-bottom:1px solid var(--line);padding-bottom:10px}.doc-list{list-style:none;margin:0;padding:0}.doc-list li{display:grid;grid-template-columns:34px 1fr auto;align-items:center;gap:10px;padding:12px 0;border-bottom:1px solid var(--line)}.doc-icon{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#e8eef0;color:#758792;font-weight:700}.doc-list li.ok .doc-icon{background:#dcefe3;color:#237348}.doc-list li.missing .doc-icon{background:#fff0db;color:#a86d19}.doc-list b{display:block;font-size:12px;font-weight:500;color:var(--text)}.doc-list small{display:block;font-size:10px;color:var(--gold);text-transform:uppercase;letter-spacing:.08em}.doc-list em{font-size:11px;font-style:normal;color:var(--muted)}.decision-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-top:24px}.decision-actions form{margin:0}.btn:disabled{cursor:not-allowed;filter:grayscale(1);opacity:.5}.note-panel{margin-top:18px;padding:20px;background:#faf6ea;border:1px solid #e5d4a7}.review-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:24px 0}.review-grid article{display:flex;align-items:flex-start;gap:14px;padding:22px;border:1px solid var(--line);background:#fbfdfd}.review-grid h3{margin:0 0 5px;font:400 17px var(--display)}.review-grid p{margin:0 0 13px;color:var(--muted);font-size:12px}.review-icon{display:grid;place-items:center;flex:0 0 36px;width:36px;height:36px;border-radius:50%;background:#dcefe3;color:#237348;font-weight:700}
.timeline-card{margin-top:32px;padding:32px;background:#ffffffc7;border:1px solid var(--line)}.timeline-card h2{margin:4px 0 26px;font:400 25px var(--display)}.proses-timeline{display:flex;align-items:flex-start;overflow-x:auto;padding:8px 4px 14px}.proses-item{position:relative;flex:1 1 0;min-width:150px;padding:0 8px;color:var(--muted);text-align:center;text-decoration:none}.proses-item:before{content:"";position:absolute;z-index:0;top:22px;left:-50%;width:100%;height:2px;background:#d7e2e8}.proses-item:first-child:before{display:none}.proses-icon{position:relative;z-index:1;display:flex;align-items:center;justify-content:center;width:44px;height:44px;margin:0 auto 12px;border-radius:50%;background:#dfe6ea;color:#7c8a94;transition:.2s}.proses-icon svg{width:22px;height:22px}.proses-item:hover .proses-icon{transform:translateY(-2px);box-shadow:0 0 0 4px rgba(165,126,44,.14)}.proses-body b{display:block;margin-bottom:5px;font:400 14px var(--display);color:var(--text)}.proses-body small{display:block;font-size:11px;line-height:1.5}.proses-item.done:before,.proses-item.current:before{background:#4c8791}.proses-item.done .proses-icon{background:#4c8791;color:#fff}.proses-item.current .proses-icon{background:var(--gold);color:#fff}.proses-item.current .proses-body b{color:var(--gold)}.proses-item.rejected .proses-icon{background:#c94d5f;color:#fff}.proses-item.rejected .proses-body b{color:#c94d5f}@media(max-width:700px){.timeline-card{padding:22px}.proses-timeline{align-items:stretch;flex-direction:column;overflow:visible}.proses-item{display:grid;grid-template-columns:52px 1fr;min-width:0;padding:10px 0;text-align:left}.proses-item:before{top:-50%;left:21px;width:2px;height:100%}.proses-icon{margin:0}.proses-body{align-self:center}}
@media(max-width:900px){.document-groups,.review-grid,.tpa-grid,.consultation-fields{grid-template-columns:1fr}.doc-list li{grid-template-columns:34px 1fr}.doc-list em{grid-column:2}}
</style>
<script>
document.querySelectorAll('.note-toggle').forEach(function(button){button.addEventListener('click',function(){var panel=button.closest('.stage-card').querySelector('.note-panel');if(panel)panel.hidden=!panel.hidden;});});
(function(){var modal=document.getElementById('fileModal'),body=document.getElementById('fileModalBody'),title=document.getElementById('fileModalTitle'),open=document.getElementById('fileModalOpen');if(!modal)return;function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');body.innerHTML='';}document.querySelectorAll('.view-file').forEach(function(button){button.addEventListener('click',function(){var url=button.dataset.fileUrl,name=button.dataset.fileTitle||'Pratinjau Berkas',ext=(url.split('.').pop()||'').toLowerCase().split('?')[0];title.textContent=name;open.href=url;if(['jpg','jpeg','png','gif','webp'].indexOf(ext)>-1)body.innerHTML='<img src="'+url+'" alt="Pratinjau berkas">';else if(ext==='pdf')body.innerHTML='<iframe src="'+url+'" title="Pratinjau berkas"></iframe>';else body.innerHTML='<p>Berkas tidak dapat dipratinjau. Gunakan tombol Buka di Tab Baru.</p>';modal.classList.add('open');modal.setAttribute('aria-hidden','false');});});modal.querySelectorAll('[data-modal-close]').forEach(function(el){el.addEventListener('click',close);});document.addEventListener('keydown',function(e){if(e.key==='Escape')close();});})();
</script>
<?php $this->load->view('pbg_pu/footer'); ?>
