<?php $heading='Tahapan Pengajuan PBG'; $top_actions='<a class="btn" href="'.base_url('pengajuan-pbg').'">Kembali ke Daftar</a>'; $this->load->view('pbg_pu/header',compact('heading','top_actions','nama_pengguna')); $labels=array(1=>'Pendaftaran Permohonan',2=>'Pemeriksaan Kelengkapan Data',3=>'Verifikasi Hasil Perbaikan',4=>'Pemeriksaan Selesai'); ?>
<?php if($this->session->flashdata('sukses')):?><div class="notice"><?= htmlspecialchars($this->session->flashdata('sukses')) ?></div><?php endif;?>
<?php $wajib=array('file_ktp','file_kepemilikan_tanah','file_data_perencana','file_pkkpr','file_rencana_teknis','file_teknis_struktur','file_checklist_mep','file_pernyataan_tataruang'); $lengkap=0; foreach($wajib as $f){if(!empty($row[$f]))$lengkap++;} $semua_lengkap=$lengkap===count($wajib); ?>
<div class="card applicant-card"><div class="applicant-head"><div><span class="badge diajukan">PBG</span><strong><?= htmlspecialchars($row['no_permohonan']) ?></strong></div><span class="badge <?= $row['status'] ?>"><?= ucfirst($row['status']) ?></span></div><div class="detail-grid"><div><small>Nama Pemohon</small><?= htmlspecialchars($row['nama_pemohon']) ?></div><div><small>NIK</small><?= htmlspecialchars($row['nik']?:'—') ?></div><div><small>Nomor HP</small><?= htmlspecialchars($row['no_hp']) ?></div><div><small>Email</small><?= htmlspecialchars($row['email']?:'—') ?></div><div class="full"><small>Alamat Bangunan</small><?= htmlspecialchars($row['alamat_bangunan']) ?></div><div><small>Jenis Bangunan</small><?= htmlspecialchars($row['jenis_bangunan']) ?></div><div><small>Kategori</small><?= ucwords(str_replace('_',' ',$row['kategori_bangunan'])) ?></div><div><small>Tanggal Pengajuan</small><?= date('d/m/Y H:i',strtotime($row['created_at'])) ?></div></div></div>

<div class="card stage-card"><div class="stage-heading"><div><p class="eyebrow">Tahap <?= $tahap ?></p><h2><?= $labels[$tahap] ?></h2></div><?php if($tahap<=2):?><span class="badge <?= $semua_lengkap?'disetujui':'diajukan' ?>"><?= $lengkap ?>/<?= count($wajib) ?> dokumen wajib</span><?php endif;?></div>
<?php if($tahap<=2):?><div class="document-groups"><?php $groups=array('Dokumen Umum'=>array('file_ktp','file_kepemilikan_tanah','file_data_perencana','file_pernyataan_tataruang'),'Bidang Arsitektur & Tata Ruang'=>array('file_pkkpr','file_rencana_teknis','file_dokumen_lingkungan'),'Bidang Struktur'=>array('file_teknis_struktur'),'Bidang MEP'=>array('file_checklist_mep')); foreach($groups as $group=>$fields):?><section><h3><?= $group ?></h3><ul class="doc-list"><?php foreach($fields as $f): $ada=!empty($row[$f]);?><li class="<?= $ada?'ok':'missing' ?>"><span class="doc-icon"><?= $ada?'✓':'!' ?></span><span><b><?= htmlspecialchars($files[$f]) ?></b><small><?= in_array($f,$wajib,true)?'Wajib':'Opsional' ?></small></span><em><?= $ada?'Tersedia':'Belum diunggah' ?></em></li><?php endforeach;?></ul></section><?php endforeach;?></div>
<?php if(!empty($row['catatan_admin'])):?><div class="notice"><b>Catatan PU terakhir</b><br><?= nl2br(htmlspecialchars($row['catatan_admin'])) ?></div><?php endif;?>
<div class="decision-actions"><?php if($tahap===1):?><?= form_open('pengajuan-pbg/ubah-tahap/'.$row['id']) ?><input type="hidden" name="tahap" value="2"><input type="hidden" name="status" value="diverifikasi"><button class="btn btn-primary" <?= !$semua_lengkap?'disabled title="Dokumen wajib belum lengkap"':'' ?>>Berkas Lengkap, Lanjut</button><?= form_close() ?><button class="btn note-toggle" type="button">Berkas Belum Lengkap</button><?php else:?><?= form_open('pengajuan-pbg/ubah-tahap/'.$row['id']) ?><input type="hidden" name="tahap" value="3"><input type="hidden" name="status" value="diverifikasi"><button class="btn btn-primary">Berkas Sudah Benar</button><?= form_close() ?><button class="btn note-toggle" type="button">Berkas Masih Salah</button><?php endif;?></div>
<div class="note-panel" hidden><?= form_open('pengajuan-pbg/ubah-tahap/'.$row['id']) ?><input type="hidden" name="tahap" value="<?= $tahap ?>"><input type="hidden" name="status" value="diverifikasi"><label>Keterangan untuk Pemohon</label><textarea name="catatan" required placeholder="Jelaskan dokumen yang kurang atau harus diperbaiki."></textarea><button class="btn" style="margin-top:10px">Simpan Keterangan</button><?= form_close() ?></div>
<?php elseif($tahap===3):?><p>PU memverifikasi hasil perbaikan dan pemeriksaan teknis dari setiap bidang.</p><div class="review-grid"><?php foreach(array('Arsitektur & Tata Ruang'=>array('file_pkkpr','file_rencana_teknis'),'Struktur'=>array('file_teknis_struktur'),'MEP'=>array('file_checklist_mep')) as $bidang=>$fields): $ok=true; foreach($fields as $f){if(empty($row[$f]))$ok=false;}?><article><span class="review-icon"><?= $ok?'✓':'!' ?></span><div><h3><?= $bidang ?></h3><p><?= $ok?'Dokumen tersedia dan siap diverifikasi.':'Dokumen bidang belum lengkap.' ?></p><span class="badge <?= $ok?'disetujui':'diajukan' ?>"><?= $ok?'Siap Diverifikasi':'Perlu Perbaikan' ?></span></div></article><?php endforeach;?></div><div class="notice"><b>Catatan PU:</b><br><?= nl2br(htmlspecialchars($row['catatan_admin']?:'Belum ada catatan.')) ?></div><div class="decision-actions"><?= form_open('pengajuan-pbg/ubah-tahap/'.$row['id']) ?><input type="hidden" name="tahap" value="4"><input type="hidden" name="status" value="disetujui"><button class="btn btn-primary">Proses Selesai</button><?= form_close() ?><button class="btn note-toggle" type="button">Perlu Perbaikan</button></div><div class="note-panel" hidden><?= form_open('pengajuan-pbg/ubah-tahap/'.$row['id']) ?><input type="hidden" name="tahap" value="3"><input type="hidden" name="status" value="diverifikasi"><label>Catatan hasil verifikasi</label><textarea name="catatan" required></textarea><button class="btn" style="margin-top:10px">Simpan Catatan</button><?= form_close() ?></div>
<?php else:?><div class="detail-grid"><div><small>No. Permohonan</small><?= htmlspecialchars($row['no_permohonan']) ?></div><div><small>Keputusan</small><span class="badge <?= $row['status'] ?>"><?= ucfirst($row['status']) ?></span></div><div class="full"><small>Catatan keputusan</small><?= nl2br(htmlspecialchars($row['catatan_admin']?:'—')) ?></div></div><?php endif;?></div>

<?php if(!empty($riwayat)):?><h2 class="section-title">Riwayat Tahapan</h2><div class="table-wrap"><table style="min-width:700px"><thead><tr><th>Tanggal</th><th>Tahap</th><th>Status</th><th>Catatan</th><th>Petugas PU</th></tr></thead><tbody><?php foreach($riwayat as $r):?><tr><td><?= date('d/m/Y H:i',strtotime($r['created_at'])) ?></td><td><?= $r['tahap'] ?></td><td><?= ucfirst($r['status']) ?></td><td><?= htmlspecialchars($r['keterangan']) ?></td><td><?= htmlspecialchars($r['actor']) ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>

<?php
$timeline = array(
  1 => array('Pendaftaran Permohonan','Permohonan PBG berhasil didaftarkan.','<rect x="6" y="3" width="12" height="18" rx="1.5"/><path d="M9 4.5V4a1.5 1.5 0 011.5-1.5h3A1.5 1.5 0 0115 4v.5"/><path d="M9 13l2.2 2.2L15.5 11"/>'),
  2 => array('Pemeriksaan Kelengkapan Data','PU memeriksa kelengkapan data dan dokumen.','<circle cx="10.5" cy="10.5" r="6"/><path d="M15 15l5 5"/>'),
  3 => array('Verifikasi Hasil Perbaikan','PU memverifikasi hasil perbaikan yang diterima.','<rect x="6" y="3" width="12" height="18" rx="1.5"/><path d="M8.5 8h7M8.5 11h7M8.5 15l2.3 2.3 4.7-5"/>'),
  4 => array('Pemeriksaan Selesai','Pemeriksaan data dan dokumen telah selesai.','<circle cx="12" cy="9" r="5.5"/><path d="M9 13.8L7 21l5-2.6 5 2.6-2-7.2"/><path d="M9.7 9.2l1.6 1.6 3-3.2"/>'),
);
?>
<section class="timeline-card" aria-labelledby="judulTimeline"><p class="eyebrow">Progres Permohonan</p><h2 id="judulTimeline">Tahapan Proses PBG</h2><div class="proses-timeline">
<?php foreach($timeline as $n=>$item): $state=$n<(int)$row['tahap']?'done':($n===(int)$row['tahap']?($row['status']==='ditolak'?'rejected':($row['status']==='disetujui'?'done':'current')):'pending'); ?>
<a class="proses-item <?= $state ?>" href="<?= base_url('pengajuan-pbg/tahap/'.$row['id'].'/'.$n) ?>"><span class="proses-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><?= $item[2] ?></svg></span><span class="proses-body"><b><?= $n ?>. <?= htmlspecialchars($item[0]) ?></b><small><?= htmlspecialchars($item[1]) ?></small></span></a>
<?php endforeach;?></div></section>
<style>
.applicant-card{margin-bottom:24px}.applicant-head,.stage-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;margin-bottom:22px}.applicant-head>div{display:flex;align-items:center;gap:12px}.stage-heading h2{margin:4px 0 0;font:400 27px var(--display)}.document-groups{display:grid;grid-template-columns:1fr 1fr;gap:22px}.document-groups section{min-width:0}.document-groups h3{font:400 17px var(--display);color:var(--gold);border-bottom:1px solid var(--line);padding-bottom:10px}.doc-list{list-style:none;margin:0;padding:0}.doc-list li{display:grid;grid-template-columns:34px 1fr auto;align-items:center;gap:10px;padding:12px 0;border-bottom:1px solid var(--line)}.doc-icon{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#e8eef0;color:#758792;font-weight:700}.doc-list li.ok .doc-icon{background:#dcefe3;color:#237348}.doc-list li.missing .doc-icon{background:#fff0db;color:#a86d19}.doc-list b{display:block;font-size:12px;font-weight:500;color:var(--text)}.doc-list small{display:block;font-size:10px;color:var(--gold);text-transform:uppercase;letter-spacing:.08em}.doc-list em{font-size:11px;font-style:normal;color:var(--muted)}.decision-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-top:24px}.decision-actions form{margin:0}.btn:disabled{cursor:not-allowed;filter:grayscale(1);opacity:.5}.note-panel{margin-top:18px;padding:20px;background:#faf6ea;border:1px solid #e5d4a7}.review-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:24px 0}.review-grid article{display:flex;align-items:flex-start;gap:14px;padding:22px;border:1px solid var(--line);background:#fbfdfd}.review-grid h3{margin:0 0 5px;font:400 17px var(--display)}.review-grid p{margin:0 0 13px;color:var(--muted);font-size:12px}.review-icon{display:grid;place-items:center;flex:0 0 36px;width:36px;height:36px;border-radius:50%;background:#dcefe3;color:#237348;font-weight:700}
.timeline-card{margin-top:32px;padding:32px;background:#ffffffc7;border:1px solid var(--line)}.timeline-card h2{margin:4px 0 26px;font:400 25px var(--display)}.proses-timeline{display:flex;align-items:flex-start;overflow-x:auto;padding:8px 4px 14px}.proses-item{position:relative;flex:1 1 0;min-width:150px;padding:0 8px;color:var(--muted);text-align:center;text-decoration:none}.proses-item:before{content:"";position:absolute;z-index:0;top:22px;left:-50%;width:100%;height:2px;background:#d7e2e8}.proses-item:first-child:before{display:none}.proses-icon{position:relative;z-index:1;display:flex;align-items:center;justify-content:center;width:44px;height:44px;margin:0 auto 12px;border-radius:50%;background:#dfe6ea;color:#7c8a94;transition:.2s}.proses-icon svg{width:22px;height:22px}.proses-item:hover .proses-icon{transform:translateY(-2px);box-shadow:0 0 0 4px rgba(165,126,44,.14)}.proses-body b{display:block;margin-bottom:5px;font:400 14px var(--display);color:var(--text)}.proses-body small{display:block;font-size:11px;line-height:1.5}.proses-item.done:before,.proses-item.current:before{background:#4c8791}.proses-item.done .proses-icon{background:#4c8791;color:#fff}.proses-item.current .proses-icon{background:var(--gold);color:#fff}.proses-item.current .proses-body b{color:var(--gold)}.proses-item.rejected .proses-icon{background:#c94d5f;color:#fff}.proses-item.rejected .proses-body b{color:#c94d5f}@media(max-width:700px){.timeline-card{padding:22px}.proses-timeline{align-items:stretch;flex-direction:column;overflow:visible}.proses-item{display:grid;grid-template-columns:52px 1fr;min-width:0;padding:10px 0;text-align:left}.proses-item:before{top:-50%;left:21px;width:2px;height:100%}.proses-icon{margin:0}.proses-body{align-self:center}}
@media(max-width:900px){.document-groups,.review-grid{grid-template-columns:1fr}.doc-list li{grid-template-columns:34px 1fr}.doc-list em{grid-column:2}}
</style>
<script>document.querySelectorAll('.note-toggle').forEach(function(button){button.addEventListener('click',function(){var panel=button.closest('.stage-card').querySelector('.note-panel');if(panel)panel.hidden=!panel.hidden;});});</script>
<?php $this->load->view('pbg_pu/footer'); ?>
