<?php $heading='Tahapan Pengajuan PBG'; $top_actions='<a class="btn" href="'.base_url('pengajuan-pbg').'">Kembali ke Daftar</a>'; $this->load->view('pbg_pu/header',compact('heading','top_actions','nama_pengguna')); $labels=array(1=>'Pendaftaran Permohonan',2=>'Pemeriksaan Kelengkapan Data',3=>'Verifikasi Hasil Perbaikan',4=>'Pemeriksaan Selesai'); ?>
<?php if($this->session->flashdata('sukses')):?><div class="notice"><?= htmlspecialchars($this->session->flashdata('sukses')) ?></div><?php endif;?>
<div class="card"><h2 style="margin-top:0">Tahap <?= $tahap ?> — <?= $labels[$tahap] ?></h2>
<?php if($tahap===1):?><p>Halaman ini menampilkan data pendaftaran dan dokumen yang dimasukkan oleh petugas PU.</p><div class="detail-grid"><div><small>No. Permohonan</small><b><?= htmlspecialchars($row['no_permohonan']) ?></b></div><div><small>Status</small><span class="badge <?= $row['status'] ?>"><?= ucfirst($row['status']) ?></span></div><div><small>Nama Pemohon</small><?= htmlspecialchars($row['nama_pemohon']) ?></div><div><small>NIK</small><?= htmlspecialchars($row['nik']?:'—') ?></div><div><small>Nomor HP</small><?= htmlspecialchars($row['no_hp']) ?></div><div><small>Email</small><?= htmlspecialchars($row['email']?:'—') ?></div><div class="full"><small>Alamat Bangunan</small><?= htmlspecialchars($row['alamat_bangunan']) ?></div><div><small>Jenis Bangunan</small><?= htmlspecialchars($row['jenis_bangunan']) ?></div><div><small>Luas</small><?= htmlspecialchars($row['luas_bangunan']?:'—') ?> m²</div></div>
<?php elseif($tahap===2):?><p>PU memeriksa kelengkapan data pemohon dan seluruh dokumen persyaratan.</p><div class="table-wrap"><table style="min-width:700px"><thead><tr><th>Dokumen</th><th>Ketersediaan</th></tr></thead><tbody><?php foreach($files as $f=>$l):?><tr><td><?= htmlspecialchars($l) ?></td><td><?= empty($row[$f])?'<span class="badge ditolak">Belum ada</span>':'<span class="badge disetujui">✓ Tersedia</span>' ?></td></tr><?php endforeach;?></tbody></table></div>
<?php elseif($tahap===3):?><p>PU mengendalikan verifikasi hasil perbaikan. Catatan proses terakhir ditampilkan agar pemeriksaan konsisten.</p><div class="notice"><b>Catatan PU:</b><br><?= nl2br(htmlspecialchars($row['catatan_admin']?:'Belum ada catatan.')) ?></div>
<?php else:?><p>Ringkasan keputusan akhir permohonan PBG.</p><div class="detail-grid"><div><small>No. Permohonan</small><?= htmlspecialchars($row['no_permohonan']) ?></div><div><small>Keputusan</small><span class="badge <?= $row['status'] ?>"><?= ucfirst($row['status']) ?></span></div><div class="full"><small>Catatan keputusan</small><?= nl2br(htmlspecialchars($row['catatan_admin']?:'—')) ?></div></div><?php endif;?>

<h2 class="section-title">Kontrol Tahap oleh PU</h2><?= form_open('pengajuan-pbg/ubah-tahap/'.$row['id']) ?><div class="grid"><div><label>Tahap</label><select name="tahap"><?php foreach($labels as $n=>$l):?><option value="<?= $n ?>" <?= $row['tahap']==$n?'selected':'' ?>><?= $n ?> — <?= $l ?></option><?php endforeach;?></select></div><div><label>Status</label><select name="status"><?php foreach(array('diajukan'=>'Diajukan','diverifikasi'=>'Diverifikasi','disetujui'=>'Disetujui','ditolak'=>'Ditolak') as $k=>$l):?><option value="<?= $k ?>" <?= $row['status']===$k?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></div><div class="full"><label>Catatan PU</label><textarea name="catatan" placeholder="Catatan pemeriksaan, perbaikan, atau keputusan..."><?= htmlspecialchars($row['catatan_admin']?:'') ?></textarea></div></div><button class="btn btn-primary" style="margin-top:20px">Simpan Tahap</button><?= form_close() ?>

<?php if(!empty($riwayat)):?><h2 class="section-title">Riwayat Tahapan</h2><div class="table-wrap"><table style="min-width:700px"><thead><tr><th>Tanggal</th><th>Tahap</th><th>Status</th><th>Catatan</th><th>Petugas PU</th></tr></thead><tbody><?php foreach($riwayat as $r):?><tr><td><?= date('d/m/Y H:i',strtotime($r['created_at'])) ?></td><td><?= $r['tahap'] ?></td><td><?= ucfirst($r['status']) ?></td><td><?= htmlspecialchars($r['keterangan']) ?></td><td><?= htmlspecialchars($r['actor']) ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div>

<?php
$timeline = array(
  1 => array('Pendaftaran Permohonan','Permohonan PBG berhasil didaftarkan.','<rect x="6" y="3" width="12" height="18" rx="1.5"/><path d="M9 4.5V4a1.5 1.5 0 011.5-1.5h3A1.5 1.5 0 0115 4v.5"/><path d="M9 13l2.2 2.2L15.5 11"/>'),
  2 => array('Pemeriksaan Kelengkapan Data','PU memeriksa kelengkapan data dan dokumen.','<circle cx="10.5" cy="10.5" r="6"/><path d="M15 15l5 5"/>'),
  3 => array('Verifikasi Hasil Perbaikan','PU memverifikasi hasil perbaikan yang diterima.','<rect x="6" y="3" width="12" height="18" rx="1.5"/><path d="M8.5 8h7M8.5 11h7M8.5 15l2.3 2.3 4.7-5"/>'),
  4 => array('Pemeriksaan Selesai','Pemeriksaan data dan dokumen telah selesai.','<circle cx="12" cy="9" r="5.5"/><path d="M9 13.8L7 21l5-2.6 5 2.6-2-7.2"/><path d="M9.7 9.2l1.6 1.6 3-3.2"/>'),
);
?>
<section class="timeline-card" aria-labelledby="judulTimeline"><p class="eyebrow">Progres Permohonan</p><h2 id="judulTimeline">Tahapan Proses PBG</h2><div class="proses-timeline">
<?php foreach($timeline as $n=>$item): $state=$n<(int)$row['tahap']?'done':($n===(int)$row['tahap']?($row['status']==='ditolak'?'rejected':($row['status']==='disetujui'?'done':'current')):'pending'); ?>
<a class="proses-item <?= $state ?>" href="<?= base_url('pengajuan-pbg/tahap/'.$row['id'].'/'.$n) ?>"><span class="proses-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><?= $item[2] ?></svg></span><span class="proses-body"><b><?= $n ?>. <?= htmlspecialchars($item[0]) ?></b><small><?= htmlspecialchars($item[1]) ?></small></span></a>
<?php endforeach;?></div></section>
<style>
.timeline-card{margin-top:32px;padding:32px;background:#ffffffc7;border:1px solid var(--line)}.timeline-card h2{margin:4px 0 26px;font:400 25px var(--display)}.proses-timeline{display:flex;align-items:flex-start;overflow-x:auto;padding:8px 4px 14px}.proses-item{position:relative;flex:1 1 0;min-width:150px;padding:0 8px;color:var(--muted);text-align:center;text-decoration:none}.proses-item:before{content:"";position:absolute;z-index:0;top:22px;left:-50%;width:100%;height:2px;background:#d7e2e8}.proses-item:first-child:before{display:none}.proses-icon{position:relative;z-index:1;display:flex;align-items:center;justify-content:center;width:44px;height:44px;margin:0 auto 12px;border-radius:50%;background:#dfe6ea;color:#7c8a94;transition:.2s}.proses-icon svg{width:22px;height:22px}.proses-item:hover .proses-icon{transform:translateY(-2px);box-shadow:0 0 0 4px rgba(165,126,44,.14)}.proses-body b{display:block;margin-bottom:5px;font:400 14px var(--display);color:var(--text)}.proses-body small{display:block;font-size:11px;line-height:1.5}.proses-item.done:before,.proses-item.current:before{background:#4c8791}.proses-item.done .proses-icon{background:#4c8791;color:#fff}.proses-item.current .proses-icon{background:var(--gold);color:#fff}.proses-item.current .proses-body b{color:var(--gold)}.proses-item.rejected .proses-icon{background:#c94d5f;color:#fff}.proses-item.rejected .proses-body b{color:#c94d5f}@media(max-width:700px){.timeline-card{padding:22px}.proses-timeline{align-items:stretch;flex-direction:column;overflow:visible}.proses-item{display:grid;grid-template-columns:52px 1fr;min-width:0;padding:10px 0;text-align:left}.proses-item:before{top:-50%;left:21px;width:2px;height:100%}.proses-icon{margin:0}.proses-body{align-self:center}}
</style>
<?php $this->load->view('pbg_pu/footer'); ?>
