<!DOCTYPE html>
<html lang="id" data-theme="light"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Kelola Aturan — Panel Admin · SIP Gatutkaca</title><link rel="icon" type="image/png" href="<?php echo base_url('assets/img/icon.png'); ?>">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Marcellus&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<style>
:root{--gold:#A57E2C;--gold2:#C9A24B;--display:'Marcellus',serif;--body:'Plus Jakarta Sans',sans-serif;--bg:#FDFBF5;--surface:#fff;--soft:#F6F1E3;--text:#152A3B;--muted:#64798b;--line:#d7e1e6}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:300 14px/1.7 var(--body)}a{text-decoration:none;color:inherit}.top{height:84px;display:flex;align-items:center;justify-content:space-between;padding:0 34px;border-bottom:1px solid var(--line);background:#fff}.brand{font:400 19px var(--display);letter-spacing:.14em;color:var(--gold)}.brand small{display:block;font:400 9px var(--body);letter-spacing:.28em;color:var(--muted)}.layout{display:flex;min-height:calc(100vh - 84px)}aside{width:240px;flex:0 0 240px;padding:38px 0;background:#fff;border-right:1px solid var(--line)}aside a{display:block;padding:13px 28px;border-left:3px solid transparent;color:var(--muted);font-size:12px;letter-spacing:.08em;text-transform:uppercase}aside a:hover,aside a.active{background:#f3f7f8;border-color:var(--gold);color:var(--gold)}main{flex:1;min-width:0;padding:48px;max-width:1400px}.eyebrow{margin:0 0 10px;color:var(--gold);font-size:11px;letter-spacing:.34em;text-transform:uppercase}h1{margin:0;font:400 clamp(30px,4vw,43px) var(--display)}.lead{max-width:720px;color:var(--muted)}.head{display:flex;justify-content:space-between;align-items:end;gap:24px;flex-wrap:wrap}.btn{display:inline-block;padding:11px 18px;border:1px solid var(--line);background:#fff;color:var(--text);font:600 10px var(--body);letter-spacing:.12em;text-transform:uppercase;cursor:pointer}.btn.gold{border-color:var(--gold2);background:var(--gold2);color:#132333}.btn.danger{border-color:#e0526b;color:#d54059}.notice{margin:24px 0;padding:14px 18px;border:1px solid #62a77c;background:#eef9f1;color:#286a42}.notice.error{border-color:#e0526b;background:#fff1f3;color:#bd3048}.table-wrap{margin-top:32px;overflow:auto;border:1px solid var(--line);background:#fff}table{width:100%;border-collapse:collapse;min-width:850px}th,td{padding:15px 17px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}th{background:#f5f8f9;color:var(--gold);font:400 11px var(--display);letter-spacing:.12em;text-transform:uppercase}td.title{font-weight:500;color:var(--text)}.tag{display:inline-block;padding:3px 10px;border:1px solid var(--line);font-size:10px;text-transform:uppercase}.tag.on{background:#e5f5e9;color:#287447}.actions{display:flex;gap:8px;flex-wrap:wrap}.actions form{margin:0}@media(max-width:800px){.layout{display:block}aside{width:auto;padding:8px;display:flex;overflow:auto}aside a{white-space:nowrap;border-left:0;border-bottom:3px solid transparent}main{padding:30px 20px}}
</style></head><body>
<header class="top"><a class="brand" href="<?php echo base_url(); ?>">SIP GATUTKACA<small>KABUPATEN CILACAP</small></a><a class="btn" href="<?php echo base_url(); ?>">Beranda</a></header>
<div class="layout"><aside><a href="<?php echo base_url('admin'); ?>">Dashboard</a><a href="<?php echo base_url('admin/pengguna'); ?>">Kelola Pengguna</a><a href="<?php echo base_url('admin/pengajuan'); ?>">Pengajuan PBG</a><a href="<?php echo base_url('admin/bangunan'); ?>">Sebaran Bangunan</a><a href="<?php echo base_url('admin/cagar-budaya'); ?>">Kelola Cagar Budaya</a><a class="active" href="<?php echo base_url('admin/aturan'); ?>">Kelola Aturan</a><a href="<?php echo base_url('admin/saran'); ?>">Saran &amp; FAQ</a><a href="<?php echo base_url('login/keluar'); ?>">Logout</a></aside>
<main><div class="head"><div><p class="eyebrow">Panel Admin</p><h1>Kelola Aturan</h1><p class="lead">Atur isi pustaka regulasi, status publikasi, dan dokumen PDF yang dapat diunduh masyarakat. ID dibuat otomatis oleh database.</p></div><a class="btn gold" href="<?php echo base_url('admin/aturan-tambah'); ?>">+ Tambah Aturan</a></div>
<?php if(!empty($sukses)):?><div class="notice"><?php echo htmlspecialchars($sukses,ENT_QUOTES,'UTF-8');?></div><?php endif;?><?php if(!empty($error)):?><div class="notice error"><?php echo htmlspecialchars($error,ENT_QUOTES,'UTF-8');?></div><?php endif;?>
<div class="table-wrap"><table><thead><tr><th>ID</th><th>Judul Aturan</th><th>Status</th><th>Dokumen PDF</th><th>Aksi</th></tr></thead><tbody>
<?php if(empty($daftar)):?><tr><td colspan="5">Belum ada aturan. Jalankan migrasi regulasi terlebih dahulu.</td></tr><?php else:foreach($daftar as $r):?><tr><td><?php echo (int)$r['id'];?></td><td class="title"><?php echo htmlspecialchars($r['judul'],ENT_QUOTES,'UTF-8');?></td><td><span class="tag <?php echo $r['aktif']?'on':'';?>"><?php echo $r['aktif']?'Tampil':'Disembunyikan';?></span></td><td><?php if(!empty($r['file_pdf'])):?><a class="btn" href="<?php echo base_url('regulasi/unduh/'.(int)$r['id']);?>">Unduh PDF</a><?php else:?><span style="color:var(--muted)">Belum diunggah</span><?php endif;?></td><td><div class="actions"><a class="btn" href="<?php echo base_url('admin/aturan-ubah/'.(int)$r['id']);?>">Ubah</a><form method="post" action="<?php echo base_url('admin/aturan-hapus/'.(int)$r['id']);?>" onsubmit="return confirm('Hapus aturan ini beserta PDF-nya?')"><button class="btn danger" type="submit">Hapus</button></form></div></td></tr><?php endforeach;endif;?>
</tbody></table></div></main></div></body></html>
