<?php
$ubah = ($row !== NULL);
$v = function ($k, $def = '') use ($row, $old) {
	if (!empty($old) && array_key_exists($k, $old)) return (string) $old[$k];
	if ($row && array_key_exists($k, $row) && $row[$k] !== NULL) return (string) $row[$k];
	return $def;
};
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?php echo $ubah ? 'Ubah' : 'Tambah'; ?> Aturan — Panel Admin · SIP Gatutkaca</title><link rel="icon" type="image/png" href="<?php echo base_url('assets/img/icon.png'); ?>"><link href="https://fonts.googleapis.com/css2?family=Marcellus&family=Plus+Jakarta+Sans:wght@300;400;500;600&display=swap" rel="stylesheet"><style>
:root{--gold:#A57E2C;--gold2:#C9A24B;--display:'Marcellus',serif;--body:'Plus Jakarta Sans',sans-serif;--bg:#FDFBF5;--soft:#f3f7f8;--text:#152A3B;--muted:#64798b;--line:#d7e1e6}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:300 14px/1.7 var(--body)}a{text-decoration:none;color:inherit}.top{height:84px;display:flex;align-items:center;justify-content:space-between;padding:0 34px;border-bottom:1px solid var(--line);background:#fff}.brand{font:400 19px var(--display);letter-spacing:.14em;color:var(--gold)}.brand small{display:block;font:400 9px var(--body);letter-spacing:.28em;color:var(--muted)}.top-actions{display:flex;align-items:center;gap:22px}.user{color:var(--gold);font-weight:600}.btn{display:inline-block;padding:11px 18px;border:1px solid var(--line);background:#fff;color:var(--text);font:600 10px var(--body);letter-spacing:.12em;text-transform:uppercase;cursor:pointer}.btn.gold{background:var(--gold2);border-color:var(--gold2)}.layout{display:flex;min-height:calc(100vh - 84px)}.sidebar{width:240px;flex:0 0 240px;padding:38px 0;background:#fff;border-right:1px solid var(--line);display:flex;flex-direction:column}.sidebar a{display:block;padding:13px 28px;border-left:3px solid transparent;color:var(--muted);font-size:12px;letter-spacing:.08em;text-transform:uppercase}.sidebar a:hover,.sidebar a.active{background:var(--soft);border-color:var(--gold);color:var(--gold)}.sidebar .logout{margin-top:auto}.content{flex:1;min-width:0}.wrap{max-width:1000px;padding:48px}.eyebrow{margin:0;color:var(--gold);font-size:11px;letter-spacing:.34em;text-transform:uppercase}h1{margin:8px 0 10px;font:400 40px var(--display)}.lead{color:var(--muted)}.notice{margin:22px 0;padding:14px 18px;border:1px solid #e0526b;background:#fff1f3;color:#bd3048}.grid{display:grid;gap:22px;margin-top:34px;padding:30px;background:#fff;border:1px solid var(--line)}.field label{display:block;margin-bottom:7px;color:var(--gold);font-size:10px;font-weight:600;letter-spacing:.14em;text-transform:uppercase}.field textarea{width:100%;min-height:130px;resize:vertical;padding:12px 14px;border:1px solid var(--line);color:var(--text);font:400 14px var(--body)}.check{display:flex!important;align-items:center;gap:10px;text-transform:none!important;letter-spacing:0!important;color:var(--text)!important}.hint{margin:7px 0 0;color:var(--muted);font-size:11px}.current{margin-top:10px;padding:12px;background:var(--soft)}.buttons{display:flex;gap:12px;flex-wrap:wrap;margin-top:25px}@media(max-width:800px){.top{padding:0 18px}.user{display:none}.layout{display:block}.sidebar{width:auto;padding:8px;display:flex;flex-direction:row;overflow:auto}.sidebar a{white-space:nowrap;border-left:0;border-bottom:3px solid transparent}.sidebar .logout{margin-top:0}.wrap{padding:30px 20px}h1{font-size:32px}.grid{padding:22px}}
</style><style>.user-menu{position:relative}.user-btn{display:flex;align-items:center;gap:8px;padding:10px 2px;border:0;background:none;color:var(--gold);font:600 14px var(--body);cursor:pointer}.user-btn svg{transition:.2s}.user-btn[aria-expanded="true"] svg{transform:rotate(180deg)}.user-panel{position:absolute;z-index:20;right:0;top:calc(100% + 10px);display:none;min-width:180px;padding:7px;background:#fff;border:1px solid var(--line);box-shadow:0 14px 38px rgba(21,42,59,.18)}.user-panel.open{display:block}.user-panel a{display:block;padding:10px 12px;font-size:12px}.user-panel a:hover{background:var(--soft);color:var(--gold)}@media(max-width:800px){.user-menu{display:none}}</style></head><body>
<header class="top"><a class="brand" href="<?php echo base_url(); ?>">SIP GATUTKACA<small>KABUPATEN CILACAP</small></a><div class="top-actions"><a class="btn" href="<?php echo base_url(); ?>">Beranda</a><div class="user-menu"><button class="user-btn" id="userBtn" type="button" aria-expanded="false" aria-controls="userPanel"><?php echo htmlspecialchars($nama_admin, ENT_QUOTES, 'UTF-8'); ?><svg width="12" height="12" viewBox="0 0 12 12" fill="none" aria-hidden="true"><path d="M2.5 4.5L6 8l3.5-3.5" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/></svg></button><div class="user-panel" id="userPanel"><a href="<?php echo base_url('pengaturan'); ?>">Pengaturan</a><a href="<?php echo base_url('login/keluar'); ?>">Logout</a></div></div></div></header>
<div class="layout"><aside class="sidebar"><a href="<?php echo base_url('admin'); ?>">Dashboard</a><a href="<?php echo base_url('admin/pengguna'); ?>">Kelola Pengguna</a><a href="<?php echo base_url('admin/pengajuan'); ?>">Pengajuan PBG</a><a href="<?php echo base_url('admin/bangunan'); ?>">Sebaran Bangunan</a><a href="<?php echo base_url('admin/cagar-budaya'); ?>">Kelola Cagar Budaya</a><a class="active" href="<?php echo base_url('admin/aturan'); ?>">Kelola Aturan</a><a href="<?php echo base_url('admin/saran'); ?>">Saran &amp; FAQ</a><a class="logout" href="<?php echo base_url('login/keluar'); ?>">Logout</a></aside>
<main class="content"><div class="wrap"><p class="eyebrow">Panel Admin</p><h1><?php echo $ubah ? 'Ubah Aturan' : 'Tambah Aturan'; ?></h1><p class="lead">PDF bersifat opsional dan dapat diunggah kemudian. Ukuran maksimum 20 MB.</p><?php if (!empty($error)): ?><div class="notice"><?php echo htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></div><?php endif; ?>
<form method="post" enctype="multipart/form-data" action="<?php echo base_url('admin/aturan-simpan' . ($ubah ? '/' . (int) $row['id'] : '')); ?>"><div class="grid"><div class="field"><label for="judul">Judul Aturan *</label><textarea id="judul" name="judul" required><?php echo htmlspecialchars($v('judul'), ENT_QUOTES, 'UTF-8'); ?></textarea></div><div class="field"><label>Status Publikasi</label><label class="check"><input type="checkbox" name="aktif" value="1" <?php echo $v('aktif', '1') === '1' ? 'checked' : ''; ?>> Tampilkan di halaman publik</label></div><div class="field"><label for="pdf">Dokumen PDF</label><input id="pdf" type="file" name="file_pdf" accept="application/pdf,.pdf"><p class="hint">Hanya PDF, maksimal 20 MB. Unggahan baru akan mengganti PDF lama.</p><?php if ($ubah && !empty($row['file_pdf'])): ?><div class="current"><a href="<?php echo base_url('regulasi/unduh/' . (int) $row['id']); ?>">Lihat PDF saat ini</a><label class="check" style="margin-top:8px"><input type="checkbox" name="hapus_pdf" value="1"> Hapus PDF saat disimpan</label></div><?php endif; ?></div></div><div class="buttons"><button class="btn gold" type="submit">Simpan Aturan</button><a class="btn" href="<?php echo base_url('admin/aturan'); ?>">Batal</a></div></form></div></main></div><script>(function(){var b=document.getElementById('userBtn'),p=document.getElementById('userPanel');if(!b||!p)return;b.addEventListener('click',function(e){e.stopPropagation();var open=p.classList.toggle('open');b.setAttribute('aria-expanded',open?'true':'false')});document.addEventListener('click',function(){p.classList.remove('open');b.setAttribute('aria-expanded','false')});})();</script></body></html>
